# Generated by Django 5.1.5 on 2025-06-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_contactus_feedback_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_data',
            name='expiration_date',
            field=models.CharField(max_length=40),
        ),
    ]
